# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Engineer.aiDemo_hiloni' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Engineer.aiDemo_hiloni

pod 'Alamofire'
pod 'SVProgressHUD'

end
